settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: test_server
  path: .
  commands: 
    install:
        status: true
        method: go build -o main.go
    run:
        status: true
        method: 
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
